---
- name: Include installation tasks
  include_tasks: install/install.yml
  tags:
    - install
    - cassandra

- name: Include configuration tasks
  include_tasks: configure/configure.yml
  tags:
    - configure
    - cassandra

- name: Include service tasks
  include_tasks: configure/service.yml
  tags:
    - service
    - cassandra
